# Generated by Django 5.2.1 on 2026-06-12 09:12

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("produits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenereReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edited_by",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("numero_facture", models.CharField(max_length=100, unique=True)),
                ("date_facture", models.DateField()),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("espece", "Espece"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("note", models.CharField(max_length=200, verbose_name="Note")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clients",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
            ],
            options={
                "db_table": "factures",
            },
        ),
        migrations.CreateModel(
            name="LigneFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edited_by",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=15)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "factures",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="factures.facture",
                    ),
                ),
                (
                    "produits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits.produit",
                    ),
                ),
            ],
            options={
                "db_table": "lignefactures",
            },
        ),
    ]
