# Generated by Django 5.2.1 on 2026-09-21 05:57

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prenoms')),
                ('date_naissance', models.CharField(max_length=100, unique=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Autres', 'Autres')], max_length=100, verbose_name='Sexe')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eleves',
            },
        ),
    ]
