# Generated by Django 5.2.1 on 2026-09-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.CharField(max_length=100, verbose_name='Date de naissance'),
        ),
    ]
