# Generated by Django 5.2.1 on 2026-09-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_alter_eleve_date_naissance'),
        ('parent_eleves', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenteleve',
            name='eleves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.eleve'),
        ),
        migrations.AlterField(
            model_name='parenteleve',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.parent'),
        ),
    ]
