# Generated by Django 5.2.1 on 2026-09-20 20:19

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annee_scolaires', '0001_initial'),
        ('enseignants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom  de la classe ')),
                ('niveau', models.CharField(max_length=200, unique=True, verbose_name='Niveau ')),
                ('effectif_max', models.PositiveIntegerField(max_length=30, verbose_name='Effectif maximum')),
                ('annees', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='annee_scolaires.anneescolaire', verbose_name='Année scolaire')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enseignants', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='enseignants.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
    ]
