# Generated by Django 5.2.1 on 2026-09-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], max_length=200, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom  de la classe '),
        ),
    ]
