# Generated by Django 5.2.1 on 2026-09-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classe_niveau_alter_classe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='effectif_max',
            field=models.PositiveBigIntegerField(verbose_name='Effectif maximum'),
        ),
    ]
