# Generated by Django 5.2.1 on 2026-09-21 09:22

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0002_alter_inscription_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Montant')),
                ('date_paiement', models.DateField()),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('scolarite', 'Scolarité'), ('cantine', 'Cantine'), ('transport', 'Transport'), ('fournitures', 'Fournitures')], max_length=100, verbose_name='Type frais')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money')], max_length=100, verbose_name='Mode de paiement')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inscriptions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscriptions.inscription')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
    ]
