# Generated by Django 5.2.1 on 2026-09-21 07:17

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_alter_eleve_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('date_inscription', models.DateField(verbose_name='Date inscription')),
                ('status', models.CharField(max_length=100, verbose_name='Statut')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eleves', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.eleve', verbose_name='Elève')),
            ],
            options={
                'db_table': 'inscriptions',
            },
        ),
    ]
