# Generated by Django 5.2.1 on 2026-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], max_length=100, verbose_name='Statut'),
        ),
    ]
