# Generated by Django 5.2.1 on 2026-09-20 16:18

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprise/logo/')),
                ('cachet', models.ImageField(blank=True, null=True, upload_to='entreprise/cachet/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='entreprise/signature/')),
                ('siege_social', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entreprises',
            },
        ),
    ]
