# Generated by Django 5.2.1 on 2026-09-21 08:48

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0002_alter_inscription_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('date_absence', models.DateField(max_length=200, verbose_name='Date absence')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('justifie', models.BooleanField(default=False, verbose_name='Justifie')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inscriptions', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscriptions.inscription', verbose_name='Inscription')),
            ],
            options={
                'db_table': 'absences',
            },
        ),
    ]
