# Generated by Django 5.2.1 on 2026-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justifie',
            field=models.CharField(choices=[('justifie', 'Justifié'), ('non_justifie', 'Non justifié')], max_length=100, verbose_name='Justification'),
        ),
    ]
