# Generated by Django 5.2.1 on 2026-09-21 06:41

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_alter_classe_effectif_max'),
        ('enseignants', '0001_initial'),
        ('matieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classes', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='classes.classe', verbose_name='Classe')),
                ('enseignants', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enseignants.enseignant', verbose_name='Enseignant')),
                ('matieres', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.matiere', verbose_name='Matière')),
            ],
            options={
                'db_table': 'enseignements',
            },
        ),
    ]
