# Generated by Django 5.2.1 on 2026-09-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classe_effectif_max'),
        ('enseignants', '0001_initial'),
        ('enseignements', '0001_initial'),
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='enseignants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enseignants.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='matieres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.matiere', verbose_name='Matière'),
        ),
    ]
