# Generated by Django 5.2.1 on 2026-09-20 18:42

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annee_scolaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('libelle', models.CharField(choices=[('Trimestre 1', 'trimestre_1'), ('Trimestre 2', 'trimestre_2'), ('Trimestre 3', 'trimestre_3')], max_length=100, verbose_name='Trimestre ')),
                ('date_debut', models.DateField(unique=True, verbose_name='Date debut')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('annees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annee_scolaires.anneescolaire')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'periodes',
            },
        ),
    ]
