# Generated by Django 5.2.1 on 2026-09-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='libelle',
            field=models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], max_length=100, verbose_name='Trimestre '),
        ),
    ]
