# Generated by Django 5.2.1 on 2026-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodes', '0002_alter_periode_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='date_debut',
            field=models.DateField(verbose_name='Date debut'),
        ),
    ]
