# Generated by Django 5.2.1 on 2026-09-20 17:29

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.IntegerField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'enseignant")),
                ('prenoms', models.CharField(max_length=200, unique=True, verbose_name="Prénoms de l'enseignant")),
                ('telephone', models.CharField(max_length=200, unique=True, verbose_name="Telephone de l'enseignant")),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enseignants',
            },
        ),
    ]
